-- Insert all 175 movies into the database
INSERT INTO movies (title, genre, year, rating, description) VALUES
('Titanic', 'Drama', 1997, 7.9, 'A love story aboard the doomed ship.'),
('Jurassic Park', 'Action', 1993, 8.1, 'Dinosaurs are brought back to life.'),
('Star Wars: A New Hope', 'Sci-Fi', 1977, 8.6, 'A young farm boy joins the Rebellion.'),
('Spider-Man: No Way Home', 'Action', 2021, 8.2, 'Spider-Man faces villains from other dimensions.'),
('Deadpool', 'Action', 2016, 8.0, 'A wisecracking mercenary gets experiment.'),
('Wonder Woman', 'Action', 2017, 7.4, 'An Amazon princess discovers her full powers.'),
('Dangal', 'Drama', 2016, 8.4, 'A former wrestler trains his daughters.'),
('3 Idiots', 'Comedy', 2009, 8.4, 'Two friends search for their long lost companion.'),
('Lagaan', 'Drama', 2001, 8.1, 'Villagers accept a challenge from British officers.'),
('Zindagi Na Milegi Dobara', 'Comedy', 2011, 8.2, 'Three friends on a bachelor trip.'),
('Queen', 'Comedy', 2013, 8.2, 'A woman goes on her honeymoon alone.'),
('Taare Zameen Par', 'Drama', 2007, 8.4, 'A teacher helps a dyslexic child.'),
('Gully Boy', 'Drama', 2019, 7.9, 'A street rapper rises from the slums.'),
('Pink', 'Thriller', 2016, 8.1, 'Three girls fight a legal battle.'),
('Andhadhun', 'Thriller', 2018, 8.2, 'A blind pianist gets embroiled in a murder mystery.'),
('Article 15', 'Crime', 2019, 8.1, 'A police officer investigates missing girls.'),
('Sholay', 'Action', 1975, 8.2, 'Two criminals help a retired police officer.'),
('Mughal-E-Azam', 'Drama', 1960, 8.1, 'A love story between a prince and a court dancer.'),
('Dilwale Dulhania Le Jayenge', 'Comedy', 1995, 8.1, 'A young couple falls in love during a trip.'),
('Kuch Kuch Hota Hai', 'Comedy', 1998, 7.5, 'A love triangle spanning years.'),
('My Name is Khan', 'Drama', 2010, 7.9, 'A man with Aspergers syndrome on a journey.'),
('Rang De Basanti', 'Drama', 2006, 8.1, 'Students fight against corruption.'),
('Baahubali 2', 'Action', 2017, 8.2, 'A warriors journey to reclaim his kingdom.'),
('RRR', 'Action', 2022, 7.9, 'Two legendary revolutionaries fight British rule.'),
('KGF Chapter 2', 'Action', 2022, 8.4, 'Rocky continues his rise to power.'),
('Pushpa', 'Action', 2021, 7.6, 'A laborer rises in the world of red sandalwood smuggling.'),
('The Pursuit of Happyness', 'Drama', 2006, 8.0, 'A struggling salesman takes custody of his son.'),
('The Green Mile', 'Drama', 1999, 8.6, 'A death row corrections officer encounters a miracle.'),
('Schindlers List', 'Drama', 1993, 9.0, 'A businessman saves lives during the Holocaust.'),
('One Flew Over the Cuckoos Nest', 'Drama', 1975, 8.7, 'A criminal pleads insanity and is admitted to a mental institution.'),
('The Pianist', 'Drama', 2002, 8.5, 'A Polish Jewish musician struggles to survive.'),
('Life is Beautiful', 'Comedy', 1997, 8.6, 'A Jewish father protects his son in a concentration camp.'),
('The Departed', 'Crime', 2006, 8.5, 'An undercover cop and a police informant.'),
('The Prestige', 'Thriller', 2006, 8.5, 'Two magicians engage in competitive one-upmanship.'),
('Memento', 'Thriller', 2000, 8.4, 'A man with short-term memory loss hunts his wifes killer.'),
('The Usual Suspects', 'Crime', 1995, 8.5, 'A sole survivor tells of the twisty events.'),
('Leon: The Professional', 'Action', 1994, 8.5, 'A professional assassin reluctantly takes care of a 12-year-old girl.'),
('Apocalypse Now', 'Drama', 1979, 8.4, 'A U.S. Army officer serves as a judge in a court-martial.'),
('Alien', 'Sci-Fi', 1979, 8.5, 'The crew of a commercial spacecraft encounters a deadly lifeform.'),
('Sunset Boulevard', 'Drama', 1950, 8.4, 'A screenwriter develops a dangerous relationship.'),
('Dr. Strangelove', 'Comedy', 1964, 8.4, 'An insane general triggers a path to nuclear holocaust.'),
('The Great Dictator', 'Comedy', 1940, 8.4, 'Dictator Adenoid Hynkel tries to expand his empire.'),
('Paths of Glory', 'Drama', 1957, 8.4, 'A colonel defends three scapegoats on trial for cowardice.'),
('Citizen Kane', 'Drama', 1941, 8.3, 'Following the death of publishing tycoon Charles Foster Kane.'),
('Singin in the Rain', 'Comedy', 1952, 8.3, 'A silent film production company transitions to sound films.'),
('Bicycle Thieves', 'Drama', 1948, 8.3, 'A man searches for his stolen bicycle.'),
('Lawrence of Arabia', 'Drama', 1962, 8.3, 'The story of T.E. Lawrence.'),
('Vertigo', 'Thriller', 1958, 8.3, 'A former police detective juggles wrestling with his personal demons.'),
('M', 'Thriller', 1931, 8.3, 'When the police in a German city are unable to catch a child-murderer.'),
('Rear Window', 'Thriller', 1954, 8.5, 'A wheelchair-bound photographer spies on his neighbors.'),
('Psycho', 'Thriller', 1960, 8.5, 'A Phoenix secretary embezzles money from her employer.'),
('Casablanca', 'Drama', 1942, 8.5, 'A cynical expatriate American cafe owner struggles to decide.'),
('City Lights', 'Comedy', 1931, 8.5, 'The Tramp struggles to help a blind flower girl.'),
('Modern Times', 'Comedy', 1936, 8.5, 'The Tramp struggles to live in modern industrial society.'),
('The Gold Rush', 'Comedy', 1925, 8.2, 'A prospector goes to the Klondike during the 1890s gold rush.'),
('Bahubali: The Beginning', 'Action', 2015, 8.0, 'A warrior rises to protect his kingdom.'),
('Tumhari Sulu', 'Comedy', 2017, 7.1, 'A housewife becomes a radio jockey.'),
('Stree', 'Comedy', 2018, 7.5, 'A horror-comedy about a mysterious woman.'),
('Uri: The Surgical Strike', 'Action', 2019, 8.2, 'Indian army conducts surgical strikes.'),
('Super 30', 'Drama', 2019, 7.9, 'A mathematician teaches underprivileged students.'),
('Bhaag Milkha Bhaag', 'Drama', 2013, 8.2, 'The story of athlete Milkha Singh.'),
('Haider', 'Drama', 2014, 8.1, 'A young man returns to Kashmir.'),
('Masaan', 'Drama', 2015, 8.1, 'Four lives intersect in Varanasi.'),
('The Avengers', 'Action', 2012, 8.0, 'Superheroes assemble to save the world.'),
('Iron Man', 'Action', 2008, 7.9, 'A billionaire builds a powered suit of armor.'),
('Captain America: The Winter Soldier', 'Action', 2014, 7.7, 'Steve Rogers struggles to embrace his role.'),
('Guardians of the Galaxy', 'Action', 2014, 8.0, 'A group of intergalactic criminals go on the run.'),
('Thor: Ragnarok', 'Action', 2017, 7.9, 'Thor must escape to save Asgard.'),
('Doctor Strange', 'Action', 2016, 7.5, 'A neurosurgeon discovers the hidden world of magic.'),
('Ant-Man', 'Action', 2015, 7.3, 'A thief becomes a shrinking superhero.'),
('The Incredibles', 'Comedy', 2004, 8.0, 'A family of superheroes is forced to hide their powers.'),
('Finding Nemo', 'Comedy', 2003, 8.2, 'A clownfish searches for his missing son.'),
('Toy Story', 'Comedy', 1995, 8.3, 'A cowboy doll is profoundly threatened.'),
('Up', 'Comedy', 2009, 8.3, 'An elderly man travels to South America.'),
('Inside Out', 'Comedy', 2015, 8.1, 'The emotions of a young girl.'),
('Coco', 'Comedy', 2017, 8.4, 'A boy enters the Land of the Dead.'),
('Frozen', 'Comedy', 2013, 7.4, 'A fearless princess sets off on a journey.'),
('Moana', 'Comedy', 2016, 7.6, 'A spirited teenager sails out on a daring mission.'),
('Zootopia', 'Comedy', 2016, 8.0, 'A rabbit cop and a cynical con artist fox.'),
('The Jungle Book', 'Comedy', 2016, 7.4, 'A man-cub raised by wolves.'),
('The Fast and the Furious', 'Action', 2001, 6.8, 'An undercover cop infiltrates a street racing crew.'),
('Fast Five', 'Action', 2011, 7.3, 'Dom and his crew plan a heist.'),
('Mission: Impossible', 'Action', 1996, 7.1, 'An agent is framed for a failed mission.'),
('John Wick', 'Action', 2014, 7.4, 'An ex-hitman comes out of retirement.'),
('The Bourne Identity', 'Action', 2002, 7.9, 'A man with amnesia discovers he is a trained assassin.'),
('Die Hard', 'Action', 1988, 8.2, 'A New York cop battles terrorists.'),
('Lethal Weapon', 'Action', 1987, 7.6, 'Two mismatched cops are paired together.'),
('Speed', 'Action', 1994, 7.3, 'A bus is rigged to explode if it goes under 50 mph.'),
('Heat', 'Crime', 1995, 8.3, 'A group of professional bank robbers.'),
('Scarface', 'Crime', 1983, 8.3, 'A Cuban immigrant becomes a drug lord.'),
('Casino', 'Crime', 1995, 8.2, 'A tale of greed, deception, money, power.'),
('Donnie Brasco', 'Crime', 1997, 7.7, 'An FBI undercover agent infiltrates the mob.'),
('L.A. Confidential', 'Crime', 1997, 8.2, 'Corruption is rampant in the police force.'),
('The Shining', 'Thriller', 1980, 8.4, 'A family heads to an isolated hotel.'),
('Jaws', 'Thriller', 1975, 8.1, 'A giant shark terrorizes a beach town.'),
('The Exorcist', 'Thriller', 1973, 8.1, 'A young girl is possessed by a demon.'),
('Aliens', 'Sci-Fi', 1986, 8.4, 'The sole survivor returns to the planet.'),
('E.T. the Extra-Terrestrial', 'Sci-Fi', 1982, 7.9, 'A troubled child befriends an alien.'),
('Close Encounters of the Third Kind', 'Sci-Fi', 1977, 7.6, 'A man becomes obsessed with UFOs.'),
('2001: A Space Odyssey', 'Sci-Fi', 1968, 8.3, 'Humanity finds a mysterious object.'),
('Blade Runner', 'Sci-Fi', 1982, 8.1, 'A blade runner must pursue replicants.'),
('The Thing', 'Sci-Fi', 1982, 8.2, 'A research team encounters an alien.'),
('Predator', 'Sci-Fi', 1987, 7.8, 'A team is hunted by an alien predator.'),
('Scream VI', 'Thriller', 2023, 6.5, 'The survivors move to New York City.'),
('John Wick: Chapter 4', 'Action', 2023, 7.7, 'John Wick uncovers a path to defeating The High Table.'),
('Fast X', 'Action', 2023, 5.8, 'Dom must confront the sins of his past.'),
('Guardians of the Galaxy Vol. 3', 'Action', 2023, 7.9, 'The team faces their most dangerous mission.'),
('Spider-Man: Across the Spider-Verse', 'Action', 2023, 8.7, 'Miles Morales catapults across the Multiverse.'),
('The Super Mario Bros. Movie', 'Comedy', 2023, 7.0, 'Mario and Luigi are transported to the Mushroom Kingdom.'),
('Indiana Jones 5', 'Action', 2023, 6.5, 'Indy faces retirement and a new adventure.'),
('Transformers: Rise of the Beasts', 'Action', 2023, 6.0, 'Optimus Prime and the Autobots take on their biggest threat.'),
('The Flash', 'Action', 2023, 6.7, 'Barry Allen uses his super speed to change the past.'),
('Ant-Man and the Wasp: Quantumania', 'Action', 2023, 6.1, 'The family finds themselves exploring the Quantum Realm.'),
('Cocaine Bear', 'Comedy', 2023, 5.9, 'A bear ingests cocaine and goes on a rampage.'),
('M3GAN', 'Thriller', 2023, 6.3, 'A lifelike doll becomes sentient.'),
('Black Adam', 'Action', 2022, 6.2, 'An ancient superhero is awakened.'),
('Wakanda Forever', 'Action', 2022, 6.7, 'The people of Wakanda fight to protect their home.'),
('Minions: The Rise of Gru', 'Comedy', 2022, 6.5, 'Young Gru plots his first scheme.'),
('Lightyear', 'Comedy', 2022, 6.1, 'The origin story of Buzz Lightyear.'),
('Nope', 'Thriller', 2022, 6.8, 'Residents attempt to capture evidence of a UFO.'),
('Bullet Train', 'Action', 2022, 7.3, 'Five assassins find themselves on a fast moving bullet train.'),
('The Northman', 'Action', 2022, 7.0, 'A Viking prince seeks revenge for his fathers murder.'),
('Morbius', 'Action', 2022, 5.2, 'A biochemist tries to cure himself of a blood disease.'),
('The Unbearable Weight of Massive Talent', 'Comedy', 2022, 7.0, 'Nicolas Cage stars as himself.'),
('Sonic the Hedgehog 2', 'Comedy', 2022, 6.5, 'Sonic and Tails face Dr. Robotnik and Knuckles.'),
('Turning Red', 'Comedy', 2022, 7.0, 'A girl turns into a giant red panda.'),
('The Revenant', 'Drama', 2015, 8.0, 'A frontiersman on a fur trading expedition.'),
('Whiplash', 'Drama', 2014, 8.5, 'A young drummer pursues perfection.'),
('La La Land', 'Comedy', 2016, 8.0, 'A jazz musician and an actress fall in love.'),
('Get Out', 'Thriller', 2017, 7.7, 'A young man visits his girlfriends family estate.'),
('Blade Runner 2049', 'Sci-Fi', 2017, 8.0, 'A young blade runner discovers a secret.'),
('The Grand Budapest Hotel', 'Comedy', 2014, 8.1, 'The adventures of a legendary concierge.'),
('Her', 'Drama', 2013, 8.0, 'A man falls in love with an AI.'),
('Moonlight', 'Drama', 2016, 7.4, 'A young mans journey of self-discovery.'),
('Once Upon a Time in Hollywood', 'Drama', 2019, 7.6, 'A fading actor and his stunt double navigate 1969 Hollywood.'),
('The Wolf of Wall Street', 'Crime', 2013, 8.2, 'The rise and fall of a stockbroker.'),
('Knives Out', 'Thriller', 2019, 7.9, 'A detective investigates a murder mystery.'),
('Ford v Ferrari', 'Action', 2019, 8.1, 'Ford challenges Ferrari at Le Mans.'),
('Everything Everywhere All at Once', 'Sci-Fi', 2022, 7.8, 'A woman explores parallel universes.'),
('The Batman', 'Action', 2022, 7.8, 'Batman investigates corruption in Gotham.'),
('No Time to Die', 'Action', 2021, 7.3, 'James Bonds final mission.'),
('Oppenheimer', 'Drama', 2023, 8.3, 'The story of the atomic bombs creation.'),
('Barbie', 'Comedy', 2023, 6.9, 'Barbie and Ken have the time of their lives.'),
('Avatar: The Way of Water', 'Sci-Fi', 2022, 7.6, 'Jake Sully lives with his newfound family.'),
('Black Panther', 'Action', 2018, 7.3, 'The king of Wakanda protects his nation.'),
('Encanto', 'Comedy', 2021, 7.2, 'A magical family lives in a magical house.'),
('Luca', 'Comedy', 2021, 7.4, 'A young boy experiences an unforgettable summer.'),
('Soul', 'Comedy', 2020, 8.0, 'A musician who has lost his passion for music.'),
('Onward', 'Comedy', 2020, 7.4, 'Two elf brothers embark on a quest.'),
('Frozen II', 'Comedy', 2019, 6.8, 'Elsa ventures into the unknown to discover her powers.');